const { detectAIGeneration } = require('./ai-image-detector');

/**
 * Confidence Scoring System for VeriSource
 * 4 Clear Levels: HIGH, MEDIUM, LOW, DISPUTED
 * v2.0: Added generator detection formatting with OOD thresholds
 */

// ─── Generator Detection ──────────────────────────────────────

const GENERATOR_DISPLAY_NAMES = {
  'authentic':         'Authentic Photo',
  'stable_diffusion':  'Stable Diffusion',
  'sdxl_realistic':    'SDXL / Realistic Vision',
  'flux':              'Flux.1',
  'dall_e_3':          'DALL-E 3',
  'grok':              'Grok (xAI)',
  'gemini_flash':      'Gemini Flash Image (Nano Banana)',
  'unknown_generator': 'Unknown Generator',
};

const OOD_HIGH_THRESHOLD   = 0.80;
const OOD_MEDIUM_THRESHOLD = 0.50;

/**
 * Format generator detection result for user-facing output.
 * Applies OOD interpretation and human-readable labels.
 *
 * @param {Object} generatorDetection - Result from GPUAIDetector.classifyGenerator()
 * @param {boolean} isAI - Whether the image was classified as AI-generated
 * @returns {Object|null} Formatted generator detection result
 */
function formatGeneratorDetection(generatorDetection, isAI) {
  if (!generatorDetection || !isAI) return null;

  // If already formatted by gpu-ai-detector.js, pass through with display name check
  if (generatorDetection.ood_level) {
    const base = (generatorDetection.detected_generator || '').replace('possibly_', '');
    return {
      ...generatorDetection,
      display_name: generatorDetection.display_name || GENERATOR_DISPLAY_NAMES[base] || base,
    };
  }

  // Raw result from RunPod — format it here
  const { generator, confidence = 0, raw_scores = {} } = generatorDetection;

  let oodLevel, finalGenerator;

  if (confidence >= OOD_HIGH_THRESHOLD) {
    oodLevel = 'confident';
    finalGenerator = generator;
  } else if (confidence >= OOD_MEDIUM_THRESHOLD) {
    oodLevel = 'uncertain';
    finalGenerator = `possibly_${generator}`;
  } else {
    oodLevel = 'unknown';
    finalGenerator = 'unknown_generator';
  }

  const baseGenerator = finalGenerator.replace('possibly_', '');
  const displayName = GENERATOR_DISPLAY_NAMES[baseGenerator] || baseGenerator;

  let verdictMessage;
  switch (oodLevel) {
    case 'confident':
      verdictMessage = `Generated by ${displayName}`;
      break;
    case 'uncertain':
      verdictMessage = `Possibly generated by ${displayName}`;
      break;
    default:
      verdictMessage = 'Unknown AI generator';
      break;
  }

  const topCandidates = Object.entries(raw_scores)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([gen, score]) => ({
      generator: gen,
      display_name: GENERATOR_DISPLAY_NAMES[gen] || gen,
      confidence: Math.round(score * 1000) / 10,
    }));

  return {
    detected_generator: finalGenerator,
    raw_generator: generator,
    display_name: displayName,
    verdict_message: verdictMessage,
    confidence: Math.round(confidence * 1000) / 10,
    ood_level: oodLevel,
    top_candidates: topCandidates,
  };
}

// ─── Confidence Scoring ───────────────────────────────────────

function calculateConfidenceScore(verification) {
  let score = 0;
  const factors = [];
  
  // Factor 1: Metadata Quality (0-30 points)
  const metadataScore = analyzeMetadata(verification);
  score += metadataScore.score;
  factors.push({
    name: 'Metadata Quality',
    score: metadataScore.score,
    max: 30,
    percentage: Math.round((metadataScore.score / 30) * 100),
    details: metadataScore.details
  });
  
  // Factor 2: External Verification (0-30 points)
  const externalScore = analyzeExternalSearch(verification);
  score += externalScore.score;
  factors.push({
    name: 'External Verification',
    score: externalScore.score,
    max: 30,
    percentage: Math.round((externalScore.score / 30) * 100),
    details: externalScore.details
  });
  
  // Factor 3: Forensic Analysis (0-25 points)
  const forensicScore = analyzeForensics(verification);
  score += forensicScore.score;
  factors.push({
    name: 'Forensic Analysis',
    score: forensicScore.score,
    max: 25,
    percentage: Math.round((forensicScore.score / 25) * 100),
    details: forensicScore.details
  });
  
  // Factor 4: Temporal Trust (0-15 points)
  const temporalScore = analyzeAge(verification);
  score += temporalScore.score;
  factors.push({
    name: 'Temporal Trust',
    score: temporalScore.score,
    max: 15,
    percentage: Math.round((temporalScore.score / 15) * 100),
    details: temporalScore.details
  });
  
  // Determine confidence level (4 levels only)
  const level = getConfidenceLevel(score, verification);

  // Format generator detection if present
  const generatorDetection = formatGeneratorDetection(
    verification.generator_detection,
    verification.ai_detection?.likely_ai_generated
  );
  
  return {
    score: Math.round(score),
    max_score: 100,
    percentage: Math.round(score),
    level: level.level,
    label: level.label,
    color: level.color,
    icon: level.icon,
    message: level.message,
    factors: factors,
    warnings: getWarnings(verification, factors),
    recommendations: getRecommendations(level.level, factors),
    ...(generatorDetection && { generator_detection: generatorDetection }),
  };
}

function analyzeMetadata(verification) {
  let score = 0;
  const details = [];
  
  // Base: Valid file type (15 points)
  if (verification.kind === 'image') {
    score += 15;
    details.push('✅ Valid image file');
  } else if (verification.kind === 'video') {
    score += 15;
    details.push('✅ Valid video file');
  } else if (verification.kind === 'audio') {
    score += 15;
    details.push('✅ Valid audio file');
  }
  
  // Has basic metadata (10 points)
  if (verification.metadata || verification.fingerprint) {
    score += 10;
    details.push('✅ Has file metadata');
  }
  
  // Has dimensions/format info (5 points)
  if (verification.metadata?.format || verification.metadata?.width) {
    score += 5;
    details.push('✅ Format metadata present');
  }
  
  // Bonus: Has camera EXIF
  if (verification.metadata?.exif && verification.metadata?.exif?.Make || verification.metadata?.exif?.Model) {
    score += 5;
    details.push('✅ Rich camera metadata');
  }
  
  return { score: Math.min(score, 30), details };
}

function analyzeExternalSearch(verification) {
  let score = 0;
  const details = [];
  
  if (verification.google_vision) {
    if (!verification.google_vision.found) {
      score += 30;
      details.push('✅ No prior online publication');
    } else {
      score += 5;
      details.push('⚠️ Found online - may be reupload');
    }
  } else {
    score += 15;
    details.push('⚠️ External search not performed');
  }
  
  return { score, details };
}

function analyzeForensics(verification) {
  let score = 20;
  const details = ['✅ No obvious manipulation detected'];
  
  if (verification.ai_detection) {
    if (verification.ai_detection.likely_ai_generated) {
      score = 0;
      details.length = 0;
      details.push('❌ AI-generated content detected (' + verification.ai_detection.ai_confidence + '% confidence)');

      // Add generator info if available
      if (verification.generator_detection) {
        const gen = formatGeneratorDetection(verification.generator_detection, true);
        if (gen) {
          details.push(`🤖 ${gen.verdict_message} (${gen.confidence}% confidence)`);
        }
      }

      if (verification.ai_detection.indicators) {
        verification.ai_detection.indicators.forEach(function(ind) {
          details.push('⚠️ ' + ind);
        });
      }
    } else if (verification.ai_detection.ai_confidence > 30) {
      score = 10;
      details.push('⚠️ Possible AI generation (' + verification.ai_detection.ai_confidence + '% confidence)');
    }
  }
  
  return { score, details };
}

function analyzeAge(verification) {
  let score = 0;
  const details = [];
  
  if (verification.verified_at || verification.created_at) {
    const uploadDate = new Date(verification.verified_at || verification.created_at);
    const now = new Date();
    const ageInDays = (now - uploadDate) / (1000 * 60 * 60 * 24);
    
    if (ageInDays < 1) {
      score = 0;
      details.push('⚠️ Uploaded < 24 hours ago');
    } else if (ageInDays < 7) {
      score = 5;
      details.push('⚠️ Uploaded < 7 days ago');
    } else if (ageInDays < 30) {
      score = 10;
      details.push('✅ Uploaded 7-30 days ago');
    } else {
      score = 15;
      details.push('✅ Uploaded 30+ days ago');
    }
  } else {
    score = 10;
    details.push('⚠️ Upload date unknown');
  }
  
  return { score, details };
}

function getConfidenceLevel(score, verification) {
  if (verification.dispute_count && verification.dispute_count > 0) {
    return {
      level: 'DISPUTED',
      label: 'DISPUTED',
      color: '#FF8C00',
      icon: '🟠',
      message: 'Ownership is under dispute'
    };
  }
  
  if (score >= 75) {
    return {
      level: 'HIGH',
      label: 'HIGH CONFIDENCE',
      color: '#28A745',
      icon: '🟢',
      message: 'Strong indicators of authenticity'
    };
  } else if (score >= 50) {
    return {
      level: 'MEDIUM',
      label: 'MEDIUM CONFIDENCE',
      color: '#FFC107',
      icon: '🟡',
      message: 'Mixed indicators - requires verification'
    };
  } else {
    return {
      level: 'LOW',
      label: 'LOW CONFIDENCE',
      color: '#DC3545',
      icon: '🔴',
      message: 'Red flags detected - potential issues'
    };
  }
}

function getWarnings(verification, factors) {
  const warnings = [];
  
  if (verification.google_vision && verification.google_vision.found) {
    warnings.push('Content found online before upload');
  }
  
  factors.forEach(factor => {
    if (factor.percentage < 50) {
      warnings.push(`Low ${factor.name.toLowerCase()}`);
    }
  });
  
  if (verification.verified_at || verification.created_at) {
    const uploadDate = new Date(verification.verified_at || verification.created_at);
    const now = new Date();
    const ageInDays = (now - uploadDate) / (1000 * 60 * 60 * 24);
    if (ageInDays < 1) {
      warnings.push('Recently uploaded - limited trust');
    }
  }

  // Generator OOD warning
  if (verification.generator_detection) {
    const gen = formatGeneratorDetection(
      verification.generator_detection,
      verification.ai_detection?.likely_ai_generated
    );
    if (gen?.ood_level === 'unknown') {
      warnings.push('AI generator could not be identified — may be a newer or unknown tool');
    }
  }
  
  return warnings;
}

function getRecommendations(level, factors) {
  const recommendations = [];
  
  if (level === 'LOW' || level === 'MEDIUM') {
    recommendations.push('Consider providing additional proof of ownership');
    recommendations.push('Link to original publication sources');
  }
  
  if (level === 'DISPUTED') {
    recommendations.push('Review dispute details');
    recommendations.push('Provide evidence of original creation');
  }
  
  return recommendations;
}

module.exports = {
  calculateConfidenceScore,
  formatGeneratorDetection,
};