// VeriSource - Confidence Scoring System v3.2
// Updated: Raised base score, AI veto power, platform-aware scoring
// v3.2: Added generator detection formatting with OOD thresholds

// ─── Generator Detection ──────────────────────────────────────

const GENERATOR_DISPLAY_NAMES = {
  'authentic':         'Authentic Photo',
  'stable_diffusion':  'Stable Diffusion',
  'sdxl_realistic':    'SDXL / Realistic Vision',
  'flux':              'Flux.1',
  'dall_e_3':          'DALL-E 3',
  'grok':              'Grok (xAI)',
  'gemini_flash':      'Gemini Flash Image (Nano Banana)',
  'gpt_image1':       'GPT Image 1',
  'midjourney':        'Midjourney',
  'unknown_generator': 'Unknown Generator',
};

const OOD_HIGH_THRESHOLD   = 0.80;
const OOD_MEDIUM_THRESHOLD = 0.50;

/**
 * Format generator detection result for user-facing output.
 * Applies OOD interpretation and human-readable labels.
 */
function formatGeneratorDetection(generatorDetection, isAI) {
  if (!generatorDetection || !isAI) return null;

  if (generatorDetection.ood_level) {
    const base = (generatorDetection.detected_generator || '').replace('possibly_', '');
    return {
      ...generatorDetection,
      display_name: generatorDetection.display_name || GENERATOR_DISPLAY_NAMES[base] || base,
    };
  }

  const { generator, confidence = 0, raw_scores = {} } = generatorDetection;
  let oodLevel, finalGenerator;

  if (confidence >= OOD_HIGH_THRESHOLD) {
    oodLevel = 'confident';
    finalGenerator = generator;
  } else if (confidence >= OOD_MEDIUM_THRESHOLD) {
    oodLevel = 'uncertain';
    finalGenerator = `possibly_${generator}`;
  } else {
    oodLevel = 'unknown';
    finalGenerator = 'unknown_generator';
  }

  const baseGenerator = finalGenerator.replace('possibly_', '');
  const displayName = GENERATOR_DISPLAY_NAMES[baseGenerator] || baseGenerator;

  let verdictMessage;
  switch (oodLevel) {
    case 'confident':  verdictMessage = `Generated by ${displayName}`; break;
    case 'uncertain':  verdictMessage = `Possibly generated by ${displayName}`; break;
    default:           verdictMessage = 'Unknown AI generator'; break;
  }

  const topCandidates = Object.entries(raw_scores)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([gen, score]) => ({
      generator: gen,
      display_name: GENERATOR_DISPLAY_NAMES[gen] || gen,
      confidence: Math.round(score * 1000) / 10,
    }));

  return {
    detected_generator: finalGenerator,
    raw_generator: generator,
    display_name: displayName,
    verdict_message: verdictMessage,
    confidence: Math.round(confidence * 1000) / 10,
    ood_level: oodLevel,
    top_candidates: topCandidates,
  };
}

// ─── Main Scoring Function ────────────────────────────────────

function calculateConfidenceScore(verificationData) {
 const {
  camera_verification,
  ai_detection,
  reverse_search,
  blockchain,
  blockchain_verification,
  polygon_verification,
  metadata,
  platform_detection,
  screenshot_detection,
  ela_analysis,
  kind
} = verificationData;

const mediaType = verificationData.mediaType || kind || 'image';

  let score = 65;
  let messages = [];
  let warnings = [];

  // ========================================
  // PLATFORM DETECTION
  // ========================================
  const isFromSocialMedia = platform_detection?.detected && platform_detection?.confidence >= 60;
  if (isFromSocialMedia) {
    messages.push(`Shared via ${platform_detection.platform} (${platform_detection.confidence}%)`);
  }

  // ========================================
  // SCREENSHOT DETECTION
  // ========================================
  if (screenshot_detection?.is_screenshot) {
    score -= 10;
    warnings.push(`Screenshot detected (${screenshot_detection.confidence}% confidence)`);
    messages.push('Screenshot - original source unknown');
  }

  // ========================================
  // CAMERA VERIFICATION
  // ========================================
  if (camera_verification?.camera_found && camera_verification?.confidence !== undefined) {
    const cameraBonus = Math.round((camera_verification.confidence / 100) * 25);
    score += cameraBonus;
    messages.push(`Camera verified: ${camera_verification.details?.model || 'Unknown'} (${camera_verification.confidence}% confidence)`);
    if (camera_verification.confidence < 50) {
      warnings.push('Camera date/release validation issues detected');
    }
  } else if (camera_verification?.camera_found) {
    score += 25;
    messages.push(`Camera verified: ${camera_verification.details?.model || 'Unknown'}`);
  } else if (camera_verification?.warnings?.length > 0) {
    score -= 5;
    warnings.push('Camera warnings detected');
  }

  // ========================================
  // EXIF METADATA BONUS
  // ========================================
  if (metadata?.has_exif) {
    score += 5;
    messages.push('EXIF metadata present');
  }

  // ========================================
  // AI DETECTION
  // ========================================
  const aiConfidence = ai_detection?.ai_confidence || 0;
  const isAI = ai_detection?.likely_ai_generated || aiConfidence >= 70;
  let aiVetoApplied = false;
  let preVetoScore = null;

  // Format generator detection if present
  const generatorDetection = formatGeneratorDetection(
    verificationData.generator_detection,
    isAI
  );

  const aiSoftwareInExif = checkForAISoftwareInExif(metadata);
  if (aiSoftwareInExif) {
    warnings.push(`AI software detected in metadata: ${aiSoftwareInExif}`);
  }

  if (aiConfidence >= 70) {
    const genMsg = generatorDetection ? ` (${generatorDetection.verdict_message})` : '';
    return buildResponse({
      score: Math.max(score - 40, 10),
      level: 'untrusted',
      label: mediaType === 'video' ? 'AI-GENERATED VIDEO' : 'AI-GENERATED IMAGE',
      color: '#9333EA',
      icon: 'cpu',
      message: `AI generation detected (${aiConfidence}% confidence)${genMsg}`,
      messages, warnings, aiVetoApplied: true, preVetoScore: score, generatorDetection,
    });

  } else if (aiConfidence >= 55) {
    const genMsg = generatorDetection ? ` (${generatorDetection.verdict_message})` : '';
    return buildResponse({
      score: Math.max(score - 30, 20),
      level: 'suspicious',
      label: mediaType === 'video' ? 'LIKELY AI-GENERATED VIDEO' : 'LIKELY AI-GENERATED IMAGE',
      color: '#9333EA',
      icon: 'cpu',
      message: `Likely AI-generated (${aiConfidence}% confidence)${genMsg}`,
      messages, warnings, aiVetoApplied: true, preVetoScore: score, generatorDetection,
    });

  } else if (aiConfidence >= 40) {
    score -= 15;
    return buildResponse({
      score: Math.min(Math.max(score, 35), 70),
      level: 'uncertain',
      label: mediaType === 'video' ? 'EDITED VIDEO' : 'EDITED IMAGE',
      color: '#F59E0B',
      icon: 'edit',
      message: `${mediaType === 'video' ? 'Video' : 'Photograph'} with AI enhancements or heavy editing (${aiConfidence}% AI indicators)`,
      messages, warnings, generatorDetection,
    });

  } else if (aiConfidence >= 25) {
    score -= 10;
    messages.push(`Some AI indicators detected (${aiConfidence}%)`);
  } else if (aiConfidence >= 15) {
    score -= 5;
    messages.push(`Minor AI indicators (${aiConfidence}%)`);
  } else {
    score += 10;
    messages.push('No significant AI patterns detected');
  }

  // ========================================
  // REVERSE IMAGE SEARCH
  // ========================================
  const reverseSearch = reverse_search || verificationData.reverse_image_search;
  if (reverseSearch?.tineye?.total_results > 0 || reverseSearch?.found_online) {
    const matchCount = reverseSearch.tineye?.total_results || reverseSearch.matches?.length || 0;
    if (matchCount > 10) {
      score += 15;
      messages.push(`Widely published (${matchCount} sources)`);
    } else if (matchCount > 3) {
      score += 10;
      messages.push(`Found on ${matchCount} sites`);
    } else {
      score += 5;
      messages.push('Limited online presence');
    }
  }

  // ========================================
  // BLOCKCHAIN VERIFICATION
  // ========================================
  const bc = blockchain || blockchain_verification;
  const poly = polygon_verification;
  
  if (bc?.status === 'confirmed' || bc?.verified) {
    score += 15;
    messages.push('Bitcoin blockchain timestamp verified');
  } else if (bc?.status === 'pending' || bc?.success) {
    score += 8;
    messages.push('Blockchain verification pending');
  }
  
  if (poly?.success && poly?.status !== 'previously_timestamped') {
    score += 10;
    messages.push('Polygon blockchain verified');
  } else if (poly?.status === 'previously_timestamped') {
    score += 12;
    messages.push('Previously verified on Polygon');
  }

  // ========================================
  // VIDEO-SPECIFIC SCORING
  // ========================================
  if (mediaType === "video" && verificationData.video_analysis?.analysis) {
    const analysis = verificationData.video_analysis.analysis;
    const aiPct = analysis.aiPercentage || 0;
    const rawVerdict = analysis.verdict;
    const finalVerdict = verificationData.video_analysis.verdict || rawVerdict;
    const deepfake = analysis.deepfakeDetection;
    const videoAiConfidence = verificationData.video_analysis?.ai_confidence || 0;
    const adjustments = verificationData.video_analysis?.ai_adjustments || [];
    
    if (deepfake?.detected) {
      const deepfakeIgnored = adjustments.some(adj => adj.includes('Deepfake signal ignored'));
      if (!deepfakeIgnored) {
        return buildResponse({
          score: Math.max(20, 100 - deepfake.confidence),
          level: 'untrusted',
          label: 'DEEPFAKE VIDEO DETECTED',
          color: '#DC2626',
          icon: 'alert-triangle',
          message: `Deepfake detected with ${deepfake.confidence}% confidence`,
          messages,
          warnings: [...warnings, 'Deepfake manipulation detected'],
          aiVetoApplied: true,
          preVetoScore: score,
          generatorDetection,
        });
      }
    }
    
    if (finalVerdict === "LIKELY_AUTHENTIC" && videoAiConfidence <= 20) {
      const authenticSignals = adjustments.filter(adj => 
        adj.includes('(-') && (
          adj.includes('LIKELY_AUTHENTIC') || adj.includes('Authentic') ||
          adj.includes('Natural') || adj.includes('Standard resolution') ||
          adj.includes('Device') || adj.includes('Multiple authentic')
        )
      ).length;
      
      const multipleAuthMatch = adjustments.find(adj => adj.includes('Multiple authentic'));
      let authenticRatio = 0;
      if (multipleAuthMatch) {
        const match = multipleAuthMatch.match(/\((\d+)\/(\d+)\)/);
        if (match) authenticRatio = parseInt(match[1]) / parseInt(match[2]);
      }
      
      const sightengine = verificationData.video_analysis?.sightengine_verification;
      const sightengineDisagrees = sightengine?.checked && sightengine?.isAI && sightengine?.confidence >= 60;
      
      if (sightengineDisagrees) {
        warnings.push(`Sightengine disagrees: ${sightengine.confidence}% AI confidence`);
      } else if (authenticRatio >= 0.75 || authenticSignals >= 5) {
        return buildResponse({
          score: Math.min(85, 100 - videoAiConfidence),
          level: 'trusted', label: 'VERIFIED VIDEO', color: '#10B981', icon: 'check-circle',
          message: 'Video appears authentic', messages, warnings, generatorDetection,
        });
      }
    }
    
    if (videoAiConfidence >= 70 || (rawVerdict === "LIKELY_AI_GENERATED" && videoAiConfidence >= 50)) {
      const suspiciousPct = analysis.suspiciousPercentage || 0;
      const effectivePct = Math.max(aiPct, suspiciousPct, videoAiConfidence, 50);
      return buildResponse({
        score: Math.max(20, 100 - effectivePct),
        level: 'untrusted', label: 'AI-GENERATED VIDEO', color: '#DC2626', icon: 'alert-triangle',
        message: `${aiPct}% of frames show AI-generation patterns`,
        messages, warnings, aiVetoApplied: true, preVetoScore: score, generatorDetection,
      });
    }
    
    if (finalVerdict === "SUSPICIOUS" || finalVerdict?.includes("POSSIBLY") || finalVerdict?.includes("POSSIBLE_AI") || (videoAiConfidence >= 40 && videoAiConfidence < 70)) {
      return buildResponse({
        score: Math.max(35, 100 - aiPct),
        level: 'suspicious', label: 'AI-ENHANCED VIDEO', color: '#F59E0B', icon: 'alert-circle',
        message: `${aiPct}% of frames show suspicious patterns`, messages, warnings, generatorDetection,
      });
    }
    
    if (finalVerdict === "AUTHENTIC" || aiPct < 20) {
      return buildResponse({
        score: Math.min(85, 100 - aiPct),
        level: 'trusted', label: 'VERIFIED VIDEO', color: '#10B981', icon: 'check-circle',
        message: 'Video appears authentic', messages, warnings, generatorDetection,
      });
    }
  }

  // ========================================
  // ELA MANIPULATION DETECTION
  // ========================================
  if (ela_analysis?.success && ela_analysis?.verdict) {
    if (ela_analysis.verdict === 'LIKELY_MANIPULATED') {
      score -= 35;
      warnings.push(`🚨 ELA: Likely manipulated (${ela_analysis.confidence}% confidence)`);
      if (ela_analysis.clusters?.length > 0) {
        warnings.push(`   Suspicious regions: ${ela_analysis.clusters.map(c => c.location).join(', ')}`);
      }
    } else if (ela_analysis.verdict === 'POSSIBLY_MANIPULATED') {
      score -= 25;
      warnings.push(`⚠️ ELA: Possibly manipulated (${ela_analysis.confidence}% confidence)`);
    } else if (ela_analysis.verdict === 'MINOR_INCONSISTENCIES') {
      score -= 15;
      warnings.push(`⚠️ ELA: Minor inconsistencies detected (${ela_analysis.manipulation_score} score)`);
      if (ela_analysis.clusters?.length > 0) {
        warnings.push(`   Edited regions: ${ela_analysis.clusters.map(c => c.location).join(', ')}`);
      }
    }
  }

  // ========================================
  // AI VETO POWER
  // ========================================
  score = Math.min(Math.max(score, 0), 100);
  preVetoScore = score;

  if (aiSoftwareInExif) {
    if (score > 25) {
      aiVetoApplied = true;
      score = 25;
      warnings.push('🚨 AI software in metadata - score capped');
    }
  } else if (aiConfidence >= 20 && aiConfidence < 40) {
    if (score > 55) {
      aiVetoApplied = true;
      score = 55;
      warnings.push(`AI indicators (${aiConfidence}%) limit maximum score`);
    }
  }

  // ========================================
  // FINAL CLASSIFICATION
  // ========================================
  if (score >= 75) {
    return buildResponse({
      score, level: 'trusted',
      label: mediaType === 'video' ? 'VERIFIED VIDEO' : 'VERIFIED IMAGE',
      color: '#10B981', icon: 'check-circle', message: messages.join(', '),
      messages, warnings, aiVetoApplied, preVetoScore: aiVetoApplied ? preVetoScore : null, generatorDetection,
    });
  } else if (score >= 60) {
    return buildResponse({
      score, level: 'acceptable',
      label: mediaType === 'video' ? 'LIKELY REAL VIDEO' : 'LIKELY REAL IMAGE',
      color: '#3B82F6', icon: 'camera', message: messages.join(', '),
      messages, warnings, aiVetoApplied, preVetoScore: aiVetoApplied ? preVetoScore : null, generatorDetection,
    });
  } else if (score >= 40) {
    const _aiCat = categorizeAIContent(metadata, aiConfidence, camera_verification);
    const _isEdited = _aiCat?.software != null;
    return buildResponse({
      score, level: 'uncertain',
      label: mediaType === 'video'
        ? (_isEdited ? 'EDITED VIDEO' : 'UNCERTAIN VIDEO')
        : (_isEdited ? 'EDITED IMAGE' : 'UNCERTAIN IMAGE'),
      color: '#F59E0B', icon: _isEdited ? 'edit' : 'help-circle', message: messages.join(', '),
      messages, warnings, aiVetoApplied, preVetoScore: aiVetoApplied ? preVetoScore : null, generatorDetection,
    });
  } else {
    return buildResponse({
      score, level: 'suspicious',
      label: mediaType === 'video' ? 'UNCERTAIN VIDEO' : 'UNCERTAIN IMAGE',
      color: '#6B7280', icon: 'help-circle', message: messages.join(', '),
      messages, warnings, aiVetoApplied, preVetoScore: aiVetoApplied ? preVetoScore : null, generatorDetection,
    });
  }
}

/**
 * Check for AI generation software in EXIF metadata
 */
function checkForAISoftwareInExif(metadata) {
  if (!metadata?.exif) return null;
  const exifString = JSON.stringify(metadata.exif).toLowerCase();
  const aiSoftware = [
    'dall-e', 'dalle', 'midjourney', 'stable diffusion', 'stablediffusion',
    'novelai', 'runway', 'pika', 'sora', 'firefly', 'adobe firefly',
    'leonardo.ai', 'ideogram', 'flux', 'comfyui', 'automatic1111'
  ];
  for (const software of aiSoftware) {
    if (exifString.includes(software)) return software;
  }
  return null;
}

/**
 * Build standardized response object
 */
function buildResponse({ score, level, label, color, icon, message, messages, warnings, aiVetoApplied, preVetoScore, generatorDetection }) {
  const iconSvgMap = {
    'check-circle': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#10B981" stroke-width="2"><path d="M22 11.08V12a10 10 0 11-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>',
    'camera': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#3B82F6" stroke-width="2"><path d="M23 19a2 2 0 01-2 2H3a2 2 0 01-2-2V8a2 2 0 012-2h4l2-3h6l2 3h4a2 2 0 012 2z"/><circle cx="12" cy="13" r="4"/></svg>',
    'edit': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#F59E0B" stroke-width="2"><path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>',
    'cpu': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="2"><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 1v3M15 1v3M9 20v3M15 20v3M20 9h3M20 14h3M1 9h3M1 14h3"/></svg>`,
    'alert-triangle': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="2"><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>`,
    'alert-circle': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>`,
    'help-circle': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#6B7280" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 015.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>'
  };

  return {
    name: level.toUpperCase(),
    label,
    percentage: Math.round(score),
    level: level.toUpperCase(),
    color,
    icon,
    iconSvg: iconSvgMap[icon] || iconSvgMap['help-circle'],
    message,
    warnings: warnings?.length > 0 ? warnings : undefined,
    factors: messages,
    ai_veto_applied: aiVetoApplied || false,
    pre_veto_score: preVetoScore || null,
    ...(generatorDetection && { generator_detection: generatorDetection }),
  };
}

/**
 * Check for editing/enhancement software in EXIF
 */
function checkForEditingSoftwareInExif(metadata) {
  if (!metadata?.exif) return null;
  const exifString = JSON.stringify(metadata.exif).toLowerCase();
  
  const aiEditingSoftware = [
    { pattern: 'topaz', name: 'Topaz Labs' },
    { pattern: 'gigapixel', name: 'Topaz Gigapixel AI' },
    { pattern: 'denoise ai', name: 'Topaz DeNoise AI' },
    { pattern: 'sharpen ai', name: 'Topaz Sharpen AI' },
    { pattern: 'luminar', name: 'Luminar AI/Neo' },
    { pattern: 'remini', name: 'Remini' },
    { pattern: 'facetune', name: 'FaceTune' },
    { pattern: 'faceapp', name: 'FaceApp' },
    { pattern: 'upscale', name: 'AI Upscaler' },
    { pattern: 'enhanced', name: 'AI Enhanced' },
    { pattern: 'super resolution', name: 'Super Resolution' },
    { pattern: 'neural', name: 'Neural Filters' },
    { pattern: 'generative fill', name: 'Generative Fill' },
    { pattern: 'content-aware', name: 'Content-Aware AI' },
  ];
  
  const traditionalEditingSoftware = [
    { pattern: 'photoshop', name: 'Adobe Photoshop' },
    { pattern: 'lightroom', name: 'Adobe Lightroom' },
    { pattern: 'camera raw', name: 'Adobe Camera Raw' },
    { pattern: 'premiere', name: 'Adobe Premiere' },
    { pattern: 'capture one', name: 'Capture One' },
    { pattern: 'dxo', name: 'DxO PhotoLab' },
    { pattern: 'darktable', name: 'Darktable' },
    { pattern: 'rawtherapee', name: 'RawTherapee' },
    { pattern: 'affinity photo', name: 'Affinity Photo' },
    { pattern: 'on1', name: 'ON1 Photo RAW' },
    { pattern: 'snapseed', name: 'Snapseed' },
    { pattern: 'vsco', name: 'VSCO' },
    { pattern: 'picsart', name: 'PicsArt' },
    { pattern: 'pixlr', name: 'Pixlr' },
    { pattern: 'canva', name: 'Canva' },
    { pattern: 'polish', name: 'Photo Polish' },
    { pattern: 'canon dpp', name: 'Canon Digital Photo Professional' },
    { pattern: 'digital photo professional', name: 'Canon DPP' },
    { pattern: 'nikon nx', name: 'Nikon NX Studio' },
    { pattern: 'sony imaging', name: 'Sony Imaging Edge' },
    { pattern: 'fujifilm', name: 'Fujifilm X RAW Studio' },
    { pattern: 'gimp', name: 'GIMP' },
    { pattern: 'krita', name: 'Krita' },
    { pattern: 'photopea', name: 'Photopea' },
  ];
  
  for (const software of aiEditingSoftware) {
    if (exifString.includes(software.pattern)) return { name: software.name, type: 'ai' };
  }
  for (const software of traditionalEditingSoftware) {
    if (exifString.includes(software.pattern)) return { name: software.name, type: 'traditional' };
  }
  return null;
}

/**
 * Determine if image is AI-generated vs AI-enhanced
 */
function categorizeAIContent(metadata, aiConfidence, cameraVerification) {
  const result = { verdict: 'VERIFIED IMAGE', category: null, software: null, softwareType: null, explanation: null };
  
  const aiGenerator = checkForAISoftwareInExif(metadata);
  if (aiGenerator) {
    return { ...result, verdict: 'AI-GENERATED IMAGE', category: 'synthetic', software: aiGenerator, explanation: `Generated by ${aiGenerator}` };
  }
  
  const editingSoftware = checkForEditingSoftwareInExif(metadata);
  const softwareName = editingSoftware?.name;
  const softwareType = editingSoftware?.type;
  
  if (aiConfidence >= 40) {
    const hasRealCamera = cameraVerification?.camera_found && cameraVerification?.is_valid;
    
    if (hasRealCamera && editingSoftware) {
      return { ...result, verdict: softwareType === 'ai' ? 'AI-ENHANCED IMAGE' : 'EDITED IMAGE', category: softwareType === 'ai' ? 'ai-enhanced' : 'edited', software: softwareName, softwareType, explanation: `Real photo edited with ${softwareName}` };
    }
    if (editingSoftware && aiConfidence < 70) {
      return { ...result, verdict: softwareType === 'ai' ? 'AI-ENHANCED IMAGE' : 'EDITED IMAGE', category: softwareType === 'ai' ? 'ai-enhanced' : 'edited', software: softwareName, softwareType, explanation: `Appears edited with ${softwareName}` };
    }
    if (aiConfidence >= 70 && !hasRealCamera) {
      return { ...result, verdict: 'AI-GENERATED IMAGE', category: 'synthetic', explanation: 'High AI indicators, no camera origin detected' };
    }
  }
  
  if (editingSoftware) {
    return { ...result, verdict: softwareType === 'ai' ? 'AI-ENHANCED IMAGE' : 'EDITED IMAGE', category: softwareType === 'ai' ? 'ai-enhanced' : 'edited', software: softwareName, softwareType, explanation: `Edited with ${softwareName}` };
  }
  
  return result;
}

module.exports = { calculateConfidenceScore, formatGeneratorDetection };
module.exports.checkForEditingSoftwareInExif = checkForEditingSoftwareInExif;
module.exports.categorizeAIContent = categorizeAIContent;